### ISSUE TITLE
Where are the documents saved?

### ISSUE THREAD

**Issue by vladdu** [gingko/client#104]
I would need to work on two different machines, and not have to export/import all the time, because it's easy to forget. Saving the data on Dropbox, for example, would solve that nicely, but it looks like the documents are not saved in files?

Another use case is making backups: which places do I have to include in a backup so that my Gingko documents are included?

**Comment by AdrianoFerrari** [comment]
Hi @vladdu . Thanks for the question & feedback.

Yes, I started saving to an internal folder instead of files, in version 2.1.
This turned out to be a mistake! I'm implementing something better for the next version.

More details in issue #105.

If you need this urgently, I can suggest a workaround (let me know). Otherwise, the new "save to files" version will be available in the next week or two, if nothing prevents me.

**Comment by vladdu** [comment]
No problem, I can wait. For reference, the database is in %HOME%\%APPDATA%\Roaming\Gingko\<long hash code>\. Closing as superseded by #105
