### ISSUE TITLE
Exporting to Word format (docx) doesn't open file automatically

### ISSUE THREAD

**Issue by AdrianoFerrari** [gingko/client#128]
Expected: after export to `docx`, the file is opened automatically by whichever program is registered to open that kind of file (usually, MS Word).

Observed: for at least one user (on Windows), exporting did not open the file.

Next steps: Reproduce, and see if it's Windows-specific, or cross-platform. It's possible that having spaces in the filename is the cause?

**Comment by SquidLord** [comment]
I don't think that _should be_ expected behavior. Exporting a file should do exactly that and only that; I don't know of a lot of editing software which allows you to export and then immediately opens an entirely other app to show you that content.

In many cases, you are exporting to a format you can't even read for someone else.

**Comment by AdrianoFerrari** [comment]
Understood. You might be right, I'll think through the cases and perhaps change it to something simpler, like a success notification.
