### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by bcdavasconcelos** [gingko/client#147]
Hello Adriano,

the desktop app looks great. Congratulations.
I would like to make a few suggestions in the spirit contributing to the improvement of the app.

1. Changing fonts is really important. I work with Ancient Greek text. The default fonts handle this script rather poorly. I was able to change them, but if I re-open the app, the default font appear back in place. Is there is a way to permanently change them, please let me know.

2. Linking between cards with Wiki-link would be terrific. By this I mean, [[article]] would take me to card with 'article' as its title, or, if there is no card with this title, it could create one.

3. Perhaps the syntax #tag could be displayed as a link to the search function with 'tag' as search term. That means, say I have I tag #to_do, if I click it, it searches for all of my cards with a to_do hashtag. Doing the same with the '@' symbol would be handy for using it with names. For both of them auto-complete would be lovely.

3. The ability to select multiple cards in oder to move them together would also be very useful. As it is right now. I have to move them individually. When working with a large text this can be rather time consuming. If there are other alternatives, please let me know.

These are all suggestions. As I say, the app if really good.
Take care,
Bernardo

**Comment by AdrianoFerrari** [comment]
Hi Bernardo.

I just released an update with ability to select fonts (implemented in [v2.3.3](https://github.com/gingko/client/releases/tag/v2.3.3)). If you have feedback on font-selection feature, let me know here: #119 .

I made a new issue to track "#tag" feature request separately, here: #148.

Since the other issues you mentioned are already on the list, I'll close this one:
- Multi-select cards : #83 
- Linking : #98
