### ISSUE TITLE
Auto-Update still broken on Linux?

### ISSUE THREAD

**Issue by gottlike** [gingko/client#149]
I noticed that there's a new version (2.3.3), but Gingko (2.3.2) is not auto-updating to it. I had to manually download it and replace the AppImage.

**Comment by AdrianoFerrari** [comment]
I'll look into this and do some more tests. Thanks for letting me know.

**Comment by AdrianoFerrari** [comment]
What I thought was the issue last time, turns out not to have been. As recommended, I was checking to see if we're in production before attempting to update.

But I was using the wrong version of the package to do so ([1.x of electron-is-dev](https://github.com/sindresorhus/electron-is-dev/commit/cadca4c1ca0067c67c1f378ed35a7e25792bf569) requires electron v3, but gingko is still on v2).

I hope I can reach some of the people who haven't been able to upgrade, somehow...

**Comment by gottlike** [comment]
Thanks Adriano. Probably it's best to just send out a mass mailing to everyone who signed up/bought..
