### ISSUE TITLE
Markdown rendering of list items inconsistent

### ISSUE THREAD

**Issue by Alex-T-H** [gingko/client#150]
Desktop version
In Edit mode it looks:
3. text blabla
_Export_
4. more blabla
5. more blabla
Hit Ctrl+Enter and it renders as
3. text blabla
Export
1. more blabla
2. more blabla
Export to Word and it displays correctly
3. text blabla
Export
4. more blabla
5. more blabla

As a sidenote: I created the list in writemonkey first and pasted it into Gingko.

**Comment by AdrianoFerrari** [comment]
I should have asked for more clarification when this issue was fresh, because I'm not sure what the problem is.

I know that the Markdown does auto numbering, so that any numbers you put in will be ignored and instead numbered automatically as 1, 2, 3, etc.

```
51. An item
3. Another item
5. A third item
```
becomes:

1. An item
2. Another item
3. A third item

To avoid this, add a slash before the period:
```
51\. An item
3\. Another item
5\. A third item
```
becomes:
51\. An item
3\. Another item
5\. A third item

**Comment by Alex-T-H** [comment]
Hello Adriano,

thanks for the hint, even if it is coming a little late.

Cheers

Axel
--------------

On Wed, 13 Nov 2019 09:43:59 -0800
Adriano Ferrari <notifications@github.com> wrote:

> I should have asked for more clarification when this issue was fresh, because I'm not sure what the problem is.
> 
> I know that the Markdown does auto numbering, so that any numbers you put in will be ignored and instead numbered automatically as 1, 2, 3, etc.
> 
> ```
> 51. An item
> 3. Another item
> 5. A third item
> ```
> becomes:
> 
> 1. An item
> 2. Another item
> 3. A third item
> 
> To avoid this, add a slash before the period:
> ```
> 51\. An item
> 3\. Another item
> 5\. A third item
> ```
> becomes:
> 51\. An item
> 3\. Another item
> 5\. A third item
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gingko/client/issues/150#issuecomment-553520691


-- 
Axel Hochgraef <a_hochgraef@hotmail.com>
