### ISSUE TITLE
Continue with the most recent tree on start up

### ISSUE THREAD

**Issue by Jos512** [gingko/client#47]
Currently when we close the Gingko app and then re-open it, we get the 'Untitled Tree'. It breaks productive flow to have to relocate and open the file you where working on. 

Worse, Gingko starts the opening process in the documents folder, not the most recent folder in which a Gingko file was saved.

**Comment by AdrianoFerrari** [comment]
This is great for the use case that many people have, which is using one big tree for reference/notes/journaling/thesis/etc.

My concern is that removing the control on what files Gingko starts with can lead to a bit of privacy leak.

Imagine this scenario:
> Alice is writing her personal journal in Gingko, and then closes it off for the night. Next day she's having coffee with a client, and pulls out her laptop, opens Gingko, and there are her innermost thoughts and frustrations revealed to her client.

Here's what I have in mind to address the "too much clicking before getting to work" issue:
1. Open the most recent document folder. Totally agree with this part.
2. Include "Recent Documents" list in the File menu, with Shortcuts for each one. Then it's just "Alt+F+1" to open last file:
![screenshot_2018-03-29_16-07-31](https://user-images.githubusercontent.com/323678/38110995-767d018c-336b-11e8-849e-487f5048e627.png)
3. Better integrate with the target OS, so that double-clicking a *.gko file or shortcut to it, opens the file. (#7)
4. Better integrate with the target OS, so that you can access "Recent Documents" via the app shortcut (Windows example here:
![](https://s11986.pcdn.co/wp-content/uploads/2008/01/jumplist.jpg)

---

All these changes would allow you to quickly get back to where you were, but still give you the control to **not** do so, if you choose.

Thoughts?

**Comment by AdrianoFerrari** [comment]
Split this into two issues:
#66 : Open at most recent folder
#65 : Create Recent Documents list

**Comment by Jos512** [comment]
> Split this into two issues

Fair enough for people that journal in Gingko. For me that isn't really what I was looking for when I opened this issue. 

But I suspect that when #7 gets implemented, I can simply make shortcut to the file in question so that a double-click on that icon opens the right one on my desktop. :slightly_smiling_face:
